"""add anketa fields

Revision ID: 45a42e8b9ab7
Revises: 7ec7d541ff9c
Create Date: 2022-07-16 09:59:55.723547

"""
from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore


# revision identifiers, used by Alembic.
revision = "45a42e8b9ab7"
down_revision = "7ec7d541ff9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vkusers", sa.Column("dch", sa.Boolean(), nullable=True))
    op.add_column("vkusers", sa.Column("gg", sa.Boolean(), nullable=True))
    op.add_column("vkusers", sa.Column("ul", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vkusers", "ul")
    op.drop_column("vkusers", "gg")
    op.drop_column("vkusers", "dch")
    # ### end Alembic commands ###
