"""add last_message_id and last_selection columns

Revision ID: 7ec7d541ff9c
Revises: 
Create Date: 2022-07-12 15:51:31.050801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec7d541ff9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vkchats', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.add_column('vkchats', sa.Column('last_selection', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vkchats', 'last_selection')
    op.drop_column('vkchats', 'last_message_id')
    # ### end Alembic commands ###
