repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [.]
  - repo: https://github.com/pre-commit/pre-commit-hooks/
    rev: v4.3.0
    hooks:
      - id: check-yaml
